FROM php:8.4.7-fpm


RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    libonig-dev \
    libssl-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libzip-dev \
    libpng-dev \
    librabbitmq-dev \
    libsodium-dev
    # supervisor
    RUN usermod -u 1000 www-data && groupmod -g 1000 www-data    
RUN docker-php-ext-install -j$(nproc) \
    bcmath \
    pdo \
    pdo_mysql \
    gd \
    opcache \
    intl \
    zip \
    soap \
    sockets \
    calendar


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get autoremove -y

WORKDIR /var/www/app